set nocompatible
set number
set ruler
set mouse=a
set showmode
set showcmd
set cursorline
set autoread
set nobackup
set noswapfile
set history=1000
set hlsearch
set incsearch
set ai smartindent
set showmatch
set scrolloff=10
set nowrap
set tabstop=4
set expandtab
set shiftwidth=4
set softtabstop=4
set statusline=%F%m%r%h%w\ [FORMAT=%{&ff}]\ [TYPE=%Y]\ [POS=%l,%v][%p%%]\ %{strftime(\"%d/%m/%y\ -\ %H:%M\")}
set statusline=[%F]%y%r%m%*%=[Line:%l/%L,Column:%c][%p%%]
set laststatus=2

syntax on
filetype on
filetype plugin on
autocmd FileType make set noexpandtab
autocmd InsertLeave,WinEnter * set cursorline
autocmd InsertEnter,WinLeave * set nocursorline

inoremap jk <esc>
colorscheme desert
