set nocompatible
set backspace=2  "help bs: 2 same as ":set backspace=indent,eol,start"

set autoindent
set smartindent
"set paste "help paste
"set nopaste

set tabstop=4
set expandtab
set shiftwidth=4
set softtabstop=4

set ignorecase
set smartcase
set hlsearch
set incsearch

set number
set ruler
set showmode
set showcmd
set showmatch
set cursorline
set scrolloff=10

set history=1000
set autoread
set nobackup
set noswapfile
set nowrap

set statusline=%F%m%r%h%w\ [FORMAT=%{&ff}]\ [TYPE=%Y]\ [POS=%l,%v][%p%%]\ %{strftime(\"%d/%m/%y\ -\ %H:%M\")}
set statusline=[%F]%y%r%m%*%=[Line:%l/%L,Column:%c][%p%%]
set laststatus=2

syntax on
filetype on
filetype plugin on
autocmd FileType make set noexpandtab
autocmd InsertLeave,WinEnter * set cursorline
autocmd InsertEnter,WinLeave * set nocursorline

colorscheme desert
